### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by lfarah** [onmyway133/XcodeColorSense#1]
Hey @onmyway133, your library is really interesting.

The only problem I found was the `README.md`, which lacks some information
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib by adding a "Installation" section, for example

What are your thoughts?

**Comment by onmyway133** [comment]
@lfarah Hi, thanks for taking a look. I just updated the README as your suggestion about the Installation section.

About https://github.com/awesome-labs/iOS-readme-template 👍 The only things I think you can improve on that is
- Move the changelog into another file. The README should not be that long
- Explicitly add LICENSE section 🎉 . I think `Meta` is so meta 😄

**Comment by lfarah** [comment]
me and @vsouza will take a look at it. Really really thanks for the feedback! 😃

**Comment by onmyway133** [comment]
@lfarah cool. As this one is good, I 'll go ahead and close it

**Comment by vsouza** [comment]
thanks @onmyway133 😄
